version: "3.8"

services:
  keycloak:
    container_name: "Keycloak"
    image: "jboss/keycloak"
    ports: 
      - "9080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    deploy:  
      restart_policy:
        condition: on-failure