version: "3.8"

services:
  elasticSearch:
    container_name: "es-node-01"
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.17.4"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=http://localhost:9201"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_USERNAME=elastic"
      - "ELASTIC_PASSWORD=changeit"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    deploy:
      restart_policy:
        condition: on-failure
  
  kibana:
    container_name: "kibana"
    image: "docker.elastic.co/kibana/kibana:8.17.4"
    ports:
      - "5601:5601"
    networks:
      - elastic
volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
