version: "3.8"

services:
  elasticSearch:
    container_name: "es-node-01"
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.11.0"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=http://localhost:9201"
    networks:
      - elastic
    deploy:
      restart_policy:
        condition: on-failure
  
  kibana:
    container_name: "kibana"
    image: "docker.elastic.co/kibana/kibana:7.11.0"
    ports:
      - "5601:5601"
    networks:
      - elastic
volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
