version: "3.8"

services: 
  mariadb: 
    container_name: "MariaDB"
    image: "arm64v8/mariadb"
    ports: 
      - "13306:3306"
    environment:
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - "./data:/var/lib/mysql"
    deploy: 
      restart_policy:
        condition: on-failure
