version: "3.8"

services:
  mariadb: 
    container_name: "MariaDB"
    image: "mariadb"
    ports: 
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./data:/var/lib/mysql"
    deploy: 
      restart_policy:
        condition: on-failure