version: "3.8"

services:
  minio:
    container_name: "MinIO"
    image: "minio/minio"
    ports: 
      - "9000:9000"
    environment:
      - MINIO_SECRET_KEY=minioadmin1
      - MINIO_ACCESS_KEY=minioadmin1
    command: ["minio", "server", "/data"]
    volumes: 
      - "./data:/data"
    deploy:
      restart_policy:
        condition: on-failure