version: "3.8"

services:
  minio:
    container_name: "MinIO"
    image: "minio/minio"
    ports: 
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=minioadmin1
      - MINIO_ROOT_PASSWORD=minioadmin1
    command: ["minio", "server", "/data"]
    volumes: 
      - "./data:/data"
    deploy:
      restart_policy:
        condition: on-failure
